title: Matthew Vollgraff
position: Senior Research Fellow
affiliation: University of California, Berkeley
email: vollgraff@berkeley.edu
keywords: Matthew Vollgraff
avatar: ./assets/img/avatar.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: 
url: https://vollgraff.com
canonical: https://vollgraff.com
remote_theme: yaoyao-liu/minimal-light
