title: Matthew Vollgraff
position: Postdoctoral Research Associate
affiliation: The Warburg Institute
(University of London)
[Bilderfahrzeuge project](https://bilderfahrzeuge.hypotheses.org)
email: vollgraff (at) bilderfahrzeuge.org
keywords: minimal academic
google_scholar: https://scholar.google.com/
avatar: ./assets/img/avatar.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: 
url: "localhost:4000"
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
