title: Matthew Vollgraff
position: Postdoctoral Research Associate
affiliation: The Warburg Institute / "Bilderfahrzeuge" project
email: vollgraff (at) bilderfahrzeuge.org
keywords: Matthew Vollgraff
avatar: ./assets/img/avatar.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: 
url: https://mvlg.github.io
canonical: https://mvlg.github.io
remote_theme: yaoyao-liu/minimal-light
